# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 18:15
from __future__ import unicode_literals

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantidade', models.IntegerField(default=1)),
            ],
            bases=(accounting.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='ProdutoReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantidade', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Produto')),
            ],
            bases=(accounting.models.BaseModel, models.Model),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='produtoreceita',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Receita'),
        ),
        migrations.AddField(
            model_name='produtodespesa',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Despesa'),
        ),
        migrations.AddField(
            model_name='produtodespesa',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Produto'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='produtos',
            field=models.ManyToManyField(through='accounting.ProdutoDespesa', to='accounting.Produto'),
        ),
        migrations.AddField(
            model_name='receita',
            name='produtos',
            field=models.ManyToManyField(through='accounting.ProdutoReceita', to='accounting.Produto'),
        ),
    ]
